세션 리스트 아이템에 onair 표시하기 #103 완료
droidknights/DroidKnights2020_App pull request #115
Opened 2020-08-24 12:00 UTC by takedawon

## Issue
- close #103 

## Overview (Required)
세션 중 라이브로 진행되는 아이템에 onair 뱃지를 표시합니다.
Session data class에 isLive 를 Boolean값으로 추가합니다.
item_session 에서 tvDate 위쪽에 onair 아이콘을 추가합니다.

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="https://user-images.githubusercontent.com/44185071/91042422-acd89700-e64c-11ea-91b2-9697ff970606.png" width="300" /> | <img src="https://user-images.githubusercontent.com/44185071/91042430-afd38780-e64c-11ea-9694-b96afcc60f00.png" width="300" />

2020-08-24 12:49 UTC, Pluu reviewed
@takedawon 현재 빌드가 되지 않는 상태이네요. PR 확인 부탁드립니다.

2020-08-24 13:57 UTC, takedawon commented
> @takedawon 현재 빌드가 되지 않는 상태이네요. PR 확인 부탁드립니다.

수정 완료했습니다!

2020-08-25 15:36 UTC, Pluu requested changes

2020-08-25 15:36 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +fun ImageView.setVisibility(onAir: Boolean) {
@takedawon 
현재 BindingAdapter는 ImageView의 Extension 기능으로도 정의되어 있습니다.
그래서 모든 ImageView가 이 함수를 호출할 수 있습니다.
일반적으로 setVisibility에서 true/false는 VISIBLE/GONE에 해당되기 때문에, 이 경우 onAir라는 표현이 맞지 않아보이네요.

`isInvisible` 라는 KTX도 존재하므로 BindingAdapter의 네이밍을 더 일반화할 필요가 있어보이네요.

2020-09-03 03:47 UTC, Pluu commented
@takedawon conflict 처리 부탁드립니다.

2021-06-03 03:16 UTC, closed without merging