Feature/#102 세션 리스트 아이템에 해당 tag 달기
droidknights/DroidKnights2020_App pull request #117
Opened 2020-08-26 10:50 UTC by seunghee63

## Issue
- close #102 

## Overview (Required)
- TagEnum 을 통해 TAG 데이터를 관리하였습니다. (각 태그의 색상은 뷰가 따로 없어 임의로 하였습니다.)
- Tag의 개수가 임의로 주어지기 때문에 세션리스트 아이템에 ChipGroup>Chip 으로 정적으로 구성되어있던 Tag뷰를 TagRecycler에 아이템을 Chip으로 바꾸어 구현하였습니다.

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="https://user-images.githubusercontent.com/41153567/91293907-b04a5a80-e7d3-11ea-9139-10cf2d7334b9.png" width="300" /> | <img src="https://user-images.githubusercontent.com/41153567/91293696-5d70a300-e7d3-11ea-8ff9-613a9cc4cc0e.png" width="300" />

2020-08-27 15:59 UTC, Pluu requested changes
@seunghee63 PR 감사합니다.

일부 항목에 오해가 발생하거나 정보노출이 문제가 될 수 있는 부분이있네요.

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +fun SessionChip.setColor(color: Int) {
@seunghee63 파라미터로 넘겨오는 컬러의 타입은 Int이기 때문에 해당 값이 Resource ID와 컬러 값(ex, 0xFF33333)인지 판단하기가 어렵습니다.

다만 Android에는 `@ColorInt`와 `@ColorRes`라는 Annotation이 있습니다.
이 Annotation 사용하면 Lint에서도 체크가 가능해집니다 :)

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +        ContextCompat.getColor(context, R.color.toolbar_textColor_black) -> ContextCompat.getColor(context, R.color.color_sessionChipText_white)
@seunghee63 Color Resource 정보는 toolbar를 위한 명칭으로 사용되었습니다.

추가로 정의해도 괜찮습니다 :)

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +    this.chipBackgroundColor = when (color) {
@seunghee63 기본 BackgroundColor의 정의가 Widget이 가지고 있는 속성 수치를 변경시 Binding Adapter에 반영이 안되는 오류가 발생할 수 있습니다.

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/res/layout/item_session_tag.xml
> +        android:paddingRight="15dp"
@seunghee63 Padding Right는 보다는 다양한 표기볍에 친화적인 Start/End 사용을 권장합니다.

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/data/Tag.kt
>      val name: String = "",
@seunghee63 TagEnum은 좋은 방법이지만, Tag와 name이 분리 되어있습니다.

Tag Class에 관련 정의하신 부분이 포함되는것이 더 필요한 정보가 연결되어 있을 듯 하네요

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/res/layout/item_session.xml
> +            name="tags"
@seunghee63 정의는 했지만 사용되지않는 것으로 보이네요.

2020-08-27 15:59 UTC, Pluu commented on androidapp/app/src/main/res/layout/item_session.xml
> +        <androidx.recyclerview.widget.RecyclerView
@seunghee63 RecycleView를 사용할 경우 Tag가 복수개가 생기는 경우 스크롤을 사용해야합니다. 이것은 참석자에게  모든 정보를 미노출하는 이슈가 발생할 수 있습니다.

2020-08-30 16:46 UTC, Pluu reviewed
Annotation을 잘못 사용해서 추가 기입남깁니다.

2020-08-30 16:46 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +fun SessionChip.setColor(@ColorRes color: Int) {
@seunghee63 `SessionChip`의 내부값을 확인하시면 Color Resource ID를 처리하는 것이 아니라 Color Int 값을 처리하는 것으로 되어 있습어요. :) 다시 확인 부탁드려요

2020-08-30 17:17 UTC, seunghee63 commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +fun SessionChip.setColor(@ColorRes color: Int) {
앗 리뷰 해 주신 내용 모두 반영한 후에 멘트 남기려고 했는데 .. 먼저 확인하고 남겨주셔서 감사합니다🙏🏻
반영하여 수정하고 멘트 남기도록 하겠습니다!

2020-08-31 19:21 UTC, seunghee63 commented on androidapp/app/src/main/java/com/droidknights/app2020/data/Tag.kt
>      val name: String = "",
@Pluu Tag와 name이 분리되어 있다는 것이 정확하게 무엇을 의미하는지 이해가 되지 않습니다.. 조금 더 설명 해 주시면 감사하겠습니다..!

2020-08-31 19:21 UTC, seunghee63 commented on androidapp/app/src/main/res/layout/item_session_tag.xml
> +        android:paddingRight="15dp"
@Pluu 수정하였습니다!

928623d

2020-08-31 19:21 UTC, seunghee63 commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +        ContextCompat.getColor(context, R.color.toolbar_textColor_black) -> ContextCompat.getColor(context, R.color.color_sessionChipText_white)
@Pluu 수정하였습니다!

f61dbb7

2020-08-31 19:21 UTC, seunghee63 commented on androidapp/app/src/main/res/layout/item_session.xml
> +        <androidx.recyclerview.widget.RecyclerView
@Pluu flexboxlayout 을 이용하여 다음과 같이 Tag의 개수가 많을 때도 스크롤 없이 모든 태그가 노출되도록 수정하였습니다.
<img src="https://user-images.githubusercontent.com/41153567/91757680-b3957a00-ec09-11ea-9fd3-8e135cdd69f3.png" width="300" />

d5257fa

2020-08-31 19:23 UTC, seunghee63 commented on androidapp/app/src/main/res/layout/item_session.xml
> +            name="tags"
@Pluu 사용되지 않은 변수와 임폴트를 제거하였습니다.

34c4577

2020-08-31 19:24 UTC, seunghee63 commented on androidapp/app/src/main/java/com/droidknights/app2020/binding/ViewBinding.kt
> +fun SessionChip.setColor(@ColorRes color: Int) {
@Pluu ColorInt 어노테이션을 사용하도록 수정하였습니다!

b616843

2020-08-31 19:35 UTC, seunghee63 reviewed
전체적으로 리뷰 해 주신 부분들을 수정했습니다.
막상 수정하다보니 리뷰 해 주신 것 중 이해가 잘 되지 않는 부분이 있어 댓글을 남겨두었습니다.

감사합니다 ☺️

2020-09-01 15:33 UTC, Pluu approved these changes
추가 코멘트 남겼습니다.

기본적인 수정은 된것으로 판단해서 approve 했습니다.

2020-09-01 15:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/data/Tag.kt
>      val name: String = "",
@seunghee63 아하 제가 좀 모호하게 이야기드렸네요.

예를 들면 아래와 같은 케이스가 있습니다.
```
1. tag: String
2. tag: Enum (name: String, color : Int ....)
```
실제로 이 2가지의 케이스에서 name을 매칭할 경우, 동일한 태그명을 맞도록 구현하는 어려움이 있습니다.
쉽게 접근한다면 String 비교가 되겠지만, Tag자체의 정보로 고유한 값을 만드는 방법도 있습니다.

1차로 지금과 같이 진행하셔도 되요 :)
---
기존 Enum을 사용할 경우 더 쉬운 관리를 할 수 있게 됩니다.

```
enum class Tag(
    val name: String,
    val color: Int
) {
    @SerializedName("type1")
    Type1("Name_Type1", ...)
    @SerializedName("type2")
    Type2("Name_Type1", ...)
    ...
}
```

이렇게 고유한 정보로 enum을 사용한다면 변경을 쉽게 가능합니다.

2020-09-01 15:33 UTC, Pluu commented
@seunghee63 Conflict이 발생했으므로 수정부탁드립니다.

2020-09-02 12:26 UTC, Pluu commented
@seunghee63 Conflict이 발생했으므로 수정부탁드립니다.

2020-09-02 13:43 UTC, seunghee63 commented
> @seunghee63 Conflict이 발생했으므로 수정부탁드립니다.

@Pluu  Conflict 발생 부분 수정 완료하였습니다!
2a2d72b

2020-09-02 13:45 UTC, Jiyoung9310 approved these changes
수고하셨습니다. 작업 감사해요 👍 💯

2020-09-02 13:45 UTC, merged