Speaker 데이터 추가
droidknights/DroidKnights2020_App pull request #120
Opened 2020-08-29 12:20 UTC by Jiyoung9310

## Issue
- close X

## Overview (Required)
- Session에 Speaker 데이터를 추가하였습니다.
- 데이터 구조는 sessions.json 을 참고해주세요.
- 로컬 데이터 최신화
```
.
.
.
    {
      "title": "Android UI에 Animation 들이붓기",
      "qnaLink": "https://forms.gle/jpVyMyZ96KZGLt3R9",
      "id": "C-1",
      "isLive": false,
      "tag": ["UI"],
      "speakerName": "안성용",
      "speaker": [
        {
          "profileImage": "https://droidknights.github.io/2020/build/img/speakers/%EC%95%88%EC%84%B1%EC%9A%A9.jpg",
          "name": "안성용",
          "introduce": "Android UI, UX, FRW에 관심있는 안드로이드 개발자입니다. 지금은 네이버웹툰에서 앱을 개발하고 있습니다."
        }
      ],
      "videoLink": "https://www.youtube.com/channel/UCjeUnwS8mHhsl600-nFJKmw",
      "time": "9/14"
    },
.
.
.
```

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2020-08-29 16:33 UTC, Pluu reviewed
@Jiyoung9310 개선 감사합니다.

추가 확인 사항이 있어서 코멘트 남겼어요.

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        val gson = GsonBuilder().create()
@Jiyoung9310 클래스 내에서 GSON 2곳에서 만드는 것은 퍼포먼스는 퍼포먼스 저하를 발생하는 부분입니다.

Dagger Inject로 개선이 되면 좋겠네요.

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/SessionRepositoryImpl.kt
> +            val gson = Gson()
@Jiyoung9310 GSON 객체를 매번 만드는 것은 퍼포먼스는 퍼포먼스 저하를 발생하는 부분입니다.

Dagger Inject로 개선이 되면 좋겠네요.

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/SessionRepositoryImpl.kt
> +            //it.toObject(Session::class.java)
@Jiyoung9310 불필요한 주석은 제거해야합니다

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +    val context: Context,
@Jiyoung9310 context/assetsName이 public으로 노출되는데 다른 이유가 있을까요?

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        //context.readJsonStringFromAsset(assetsName)?.toSessionList().orEmpty()
@Jiyoung9310 불필요한 주석은 제거해야합니다

2020-08-29 16:33 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        return gson.fromJson(result, collectionType) as ENTITY
@Jiyoung9310 혹시 result가 null일때 체크를 해보셨나요?

2020-08-29 17:20 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        val gson = GsonBuilder().create()
@Pluu Gson di로 주입받도록 수정하였습니다!

2020-08-29 17:20 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/SessionRepositoryImpl.kt
> +            val gson = Gson()
@Pluu Gson di로 주입받도록 수정하였습니다!

2020-08-29 17:20 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/SessionRepositoryImpl.kt
> +            //it.toObject(Session::class.java)
@Pluu 불필요한 주석 제거하였습니다!

2020-08-29 17:20 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        //context.readJsonStringFromAsset(assetsName)?.toSessionList().orEmpty()
@Pluu 불필요한 주석 제거하였습니다!

2020-08-29 17:23 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +    val context: Context,
@Pluu 프로퍼티 초기화할 때만 쓰이도록 변경하였습니다

2020-08-29 17:24 UTC, Jiyoung9310 commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +        return gson.fromJson(result, collectionType) as ENTITY
@Pluu try-catch 에서 파일을 제대로 읽지 못할 경우 throw Exception 처리 추가하였습니다

2020-08-30 01:31 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
> +    val context: Context,
@Jiyoung9310 이전 내용에서는 private가 없기때문에 외부에서 context를 접근할 수 있다는 부분의 리뷰였어요. :)
어떻게든 필요한 부분만 외부로 연결되면 되는 내용이였어요

2020-08-30 01:49 UTC, Pluu requested changes
@Jiyoung9310 앱 캐시를 제거한 상태에서 AssertUtils의 코드를 아래처럼 작성하면 앱이 종료되요.

```
inline fun <reified ENTITY> Context.loadJson(gson: Gson, fileName: String): ENTITY {
    throw Exception("Can not read Json file")
}
```

2020-08-30 01:49 UTC, Pluu commented on androidapp/app/src/main/java/com/droidknights/app2020/common/AssetUtils.kt
> +        throw Exception("Can not read Json file", e)
@Jiyoung9310 여기에서 throw로 에러를 외부로 보냈지만, 실제로 사용하는 측에서의 try~catch  등 예외처리가 누락되어서 앱이 종료됩니다.

```
Caused by: java.lang.Exception: Can not read Json file
```

그래서 여기에서는 try-catch는 불필요한 동작이 됩니다.

PrePackagedDbImpl에서 try~catch를 대응하는게 더 자유로운 대응을 할 수 있어요.

2020-08-30 05:58 UTC, Pluu approved these changes
수고하셨습니다 👍

2020-08-30 07:13 UTC, merged