툴바 스타일 정의
droidknights/DroidKnights2020_App pull request #147
Opened 2020-09-02 14:39 UTC by yands11

## Issue
- close #142 

## Overview (Required)
- 툴바 디자인 적용

## Screenshot
Before | After
:--: | :--:
None | <img src="https://user-images.githubusercontent.com/14346588/91997805-70581a00-ed75-11ea-8dde-eb7fda11b127.png" width="300" />

2020-09-02 15:03 UTC, Pluu requested changes
디자인 부분 이슈가 있네요. 확인 부탁드립니다.

2020-09-02 15:03 UTC, Pluu commented on androidapp/app/src/main/res/layout/schedule_fragment.xml
> +                android:paddingTop="@dimen/toolbar_height"
@yands11 toolbar 높이 하드코딩은 권장하는 형태가 아닙니다.

2020-09-02 15:03 UTC, Pluu commented on androidapp/app/src/main/res/layout/schedule_fragment.xml
> +        <androidx.appcompat.widget.Toolbar
@yands11 디자인에서는 스케쥴 탭에서는 상단 툴바가 존재하지 않습니다.

2020-09-02 15:16 UTC, Pluu commented on androidapp/app/src/main/res/layout/schedule_fragment.xml
> +        <androidx.appcompat.widget.Toolbar
@yands11 해당 화면은 상단 디자인이 다르지만, 디테일한 부분은 스킵하겠습니다.

2020-09-02 15:17 UTC, Pluu commented on androidapp/app/src/main/res/layout/fragment_home.xml
> +        <androidx.recyclerview.widget.RecyclerView
![device-2020-09-02-235426](https://user-images.githubusercontent.com/1534926/92002433-d1362100-ed7a-11ea-9d0a-0b9ce51d9851.png)

FrameLayout을 사용했으므로 예시와 같이 Toolbar와 하단 리스트가 켭쳐서 노출되네요.

2020-09-03 01:39 UTC, yands11 commented
제플린 디자인 시안으로는 확인할 수 없는 부분이 있었는데 미리 질문을 드리고 진행했어야 하는데 죄송합니다.
CoordinatorLayout 을 활용해서 해결해보려고하는데 
툴바가 스크롤 상관없이 고정이 되어야할까요? 아니면 같이 스크롤이 되어야 할까요?

2020-09-03 03:46 UTC, Pluu commented
@yands11 괜찮습니다. UI , UX는 다양하게 열려있으니 겹쳐지는 홈 Fragment 문제만 해결하는 것으로 진행하면 될 것 같네요.

2020-09-03 11:15 UTC, yands11 commented
ScheduleFragmet도 동일한 이슈가 발생되어 LinearLayout으로 모두 교체하였습니다.

2020-09-03 15:34 UTC, Pluu approved these changes
👍 수고하셨습니다.

2020-09-04 14:05 UTC, Jiyoung9310 commented
@yands11 컨플릭이 났는데, 수정 가능하실까요?

2020-09-05 00:20 UTC, yands11 commented
네 확인해볼게요!

2020-09-05 00:27 UTC, yands11 commented
@Jiyoung9310 컨플릭 해결했습니다 :)

2020-09-05 02:00 UTC, Jiyoung9310 approved these changes
감사합니다!

2020-09-05 02:00 UTC, merged